
# Name your project! Project names should contain only lowercase characters and underscores.
name: 'Silverscreen'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for connecting to a database.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure threshold variables for data_tests:
vars:
  threshold_date: '2024-01-01' # used in test: earlier_than_threshold_date   

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  Silverscreen:
    staging:
      +materialized: view
    integration:
      +materialized: view
    consumer:
      +materialized: table

# Configuring tests
tests:
  +severity: warn  