version: 2

models:
# For staging models description is reduced as column names are self explanatory
# Also testing will be reduced to minimum possible for tables where we have done initial source testing and no transformations or cleaning 

  - name: stg_movie_catalog
    description: Holds descriptive and qualitative movie information about directors, length, release date and more.
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: movie_title
        tests:
          - not_null
      - name: movie_genre
        tests:
          - not_null
      - name: movie_director
        tests:
          - not_null
      - name: movie_studio
        tests:
          - not_null
      - name: movie_pg_rating
        tests:
          - not_null
  - name: stg_invoices
    description: Holds movie rental costs in form of individual invoices for a movie for a given time for a specific movie theatre.
    columns:
      - name: movie_id
        tests:
          - not_null
          - relationships:
              field: movie_id
              to: ref('stg_movie_catalog')
      - name: cinema_id
        tests:
          - not_null
      - name: rental_month
        tests:
          - not_null
      - name: sum_rental_costs
        tests:
          - not_null
          - not_negative
  - name: stg_sales_cinema_01
    description: Holds sales figures of movie theatre 1
    columns:
      - name: sales_month
        description: Year and month of movie tickets sold.
        tests:
          - not_null
      - name: movie_id
        description: Foreign key, primary key of movie. 
        tests:
          - not_null
          - relationships:
              arguments:
                field: 'movie_id'
                to: ref('stg_movie_catalog')
      - name: tickets_sold
        tests:
          - not_null
          - not_negative
        description: Total tickets sold for this movie this month in this theatre.
      - name: total_revenue
        description: Total revenue in USD for tickets sold for this movie this month this theatre.
        tests:
          - not_null
          - not_negative
      - name: cinema_id
        description: ID of movie theatre of silverscreen where movie is been shown.
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: '=1'
  - name: stg_sales_cinema_02
    description: Similar to stg_sales_cinema_01 but for movie theatre 2.
    columns:
      - name: sales_month
        description: Year and month of movie tickets sold.
        tests:
          - not_null
      - name: movie_id
        description: Foreign key, primary key of movie. 
        tests:
          - not_null
          - relationships:
              arguments:
                field: 'movie_id'
                to: ref('stg_movie_catalog')
      - name: tickets_sold
        tests:
          - not_null
          - not_negative
        description: Total tickets sold for this movie this month in this theatre.
      - name: total_revenue
        description: Total revenue in USD for tickets sold for this movie this month this theatre.
        tests:
          - not_null
          - not_negative
      - name: cinema_id
        description: ID of movie theatre of silverscreen where movie is been shown.
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: '=2'
  - name: stg_sales_cinema_03
    description: Similar to stg_sales_cinema_01 but for movie theatre 3.
    columns:
      - name: sales_month
        description: Year and month of movie tickets sold.
        tests:
          - not_null
      - name: movie_id
        description: Foreign key, primary key of movie. 
        tests:
          - not_null
          - relationships:
              arguments:
                field: 'movie_id'
                to: ref('stg_movie_catalog')
      - name: tickets_sold
        tests:
          - not_null
          - not_negative
        description: Total tickets sold for this movie this month in this theatre.
      - name: total_revenue
        description: Total revenue in USD for tickets sold for this movie this month this theatre.
        tests:
          - not_null
          - not_negative
      - name: cinema_id
        description: ID of movie theatre of silverscreen where movie is been shown.
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: '=3'
