
models:
# Consumer / marts models
  - name: mrt_movies_financial_performance
    description: Holds final reporting facts and dimensions about movies shown in one of our movies. Data is aggregated on monthly level. Holds information about movie, cinema, month, rental costs, revenue and number of sold tickets. As well many qualitative information about the movie itself which can be used for analytical purposes.
    columns:
      - name: movie_title
        description: Title of shown movie.
        tests:
          - not_null
      - name: movie_genre
        description: Genre of shown movie.
      - name: movie_studio
        description: Name of studio which has produced the movie.
      - name: movie_budget_category
        description: Budget spend for production of movie. Three categories. Small (<100 Mio USD), Medium (100-200 Mio USD), Large (>200 Mio USD).
      - name: movie_director
        description: Name of director of movie.
      - name: movie_pg_rating
        description: PG (parental guidance) rating of movie.
      - name: movie_length_min
        description: Lenght of movie in minutes.
      - name: movie_rental_costs
        description: Rental costs silver screen had to spend for that movie. Aggregated on months and cinemas for every movie.
        tests:
          - not_null
          - not_negative
      - name: month
        description: Year and month in which the movie was shown and the figures relate to that month.
        tests:
          - not_null
          - not_earlier_than_threshold_date
      - name: cinema_id
        description: Identifies the movie theatre where the movie was shown.
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1,2,3]
      - name: sum_tickets_sold
        description: Number of tickets sold for that movie in that month in the movie theatre.
        tests:
          - not_null
          - not_negative
      - name: sum_total_revenue
        description: Total revenue in USD generated by ticket sales for that movie in that cinema in given month.