
version: 2

sources:
    - name: raw
      database: silverscreen
      schema: raw
      tables:
        - name: invoices
        - name: movies
        - name: sales_cinema_01
        - name: sales_cinema_02
        - name: sales_cinema_03


models:
  - name: stg_sales_cinema_01
    description: Holds sales figures of movie theatre 1
    columns:
      - name: month
        description: Year and month of movie tickets sold.
        tests:
          - not_null
          - is_not_negative
      - name: movie_id
        description: Foreign key, primary key of movie. 
        tests:
          - not_null
      - name: tickets_sold
        description: Total tickets sold for this movie this month in this theatre.
        tests:
          - not_null
          - is_not_negative
      - name: total_revenue
        description: Total revenue in USD for tickets sold for this movie this month this theatre.
        tests:
          - not_null
          - is_not_negative
      - name: cinema_id
        description: ID of movie theatre of silverscreen where movie is been shown.
        tests:
          - not_null
          - accepted_values:
              values:
                - 1
                - 2
                - 3
      - name: load_timestamp
        description: Timestamp when data has been loaded

  - name: int_movie_sales
    description: Movie sales figures of all movie theatres united. Figures are aggregated on monthly level.
  
  
  
  - name: int_movie_rental_costs
    columns:
      - name: movie_id
        description: ID of shown movie.
        tests:
          - not_null
      - name: movie_title
        description: Title of shown movie.
        tests:
          - not_null
      - name: movie_genre
        description: Genre of shown movie.
      - name: movie_studio
        description: Name of studio which produced the movie.
      - name: movie_studio_country
        description: Name of country of studio which produced the movie.
      - name: movie_budget
        description: Production budget of movie.
      - name: movie_director
        description: Name of directory of movie.
      - name: movie_pg_rating
        description: Name of PG rating of movie.
      - name: movie_length_min
        description: Length of movie in minutes.
      - name: month
        description: Year and month of figures.
        tests:
          - not_null
      - name: cinema_id
        description: ID of silver screen cinema where movie was shown.
        tests:
          - not_null
          - accepted_values:
              values:
                - 1
                - 2
                - 3
      - name: movie_rental_costs
        description: Rental costs silver screen pays to movie distributers for shown movies.
        tests:
          - not_null
          - is_not_negative

  - name: int_sales_cinema_01_aggregate_on_month
    description: Aggregates daily sales figures from cinema 1 on monthly granularity. Column description see model stg_sales_cinema_01

  - name: int_sales_cinema_02_aggregate_on_month
    description: Aggregates daily sales figures from cinema 2 on monthly granularity. Column description see model stg_sales_cinema_02